export const START_GET_DOGS = 'START_GET_DOGS';
export const  SUCCES_GET_DOGS = 'SUCCES_GET_DOGS';
export const  ERROR_GET_DOGS = 'SUCCES_GET_DOGS';
export const START_GET_DOGS_BY_BREED = 'START_GET_DOGS_BY_BREED';
export const SUCCES_GET_DOGS_BY_BREED = 'SUCCES_GET_DOGS_BY_BREED';
export const ERROR_GET_DOGS_BY_BREED = 'ERROR_GET_DOGS_BY_BREED';
export const ORDER_ALPHABETICAL_DOWN = 'ORDER_ALPHABETICAL_DOWN';
export const ORDER_ALPHABETICAL_UP = 'ORDER_ALPHABETICAL_UP';
export const ORDER_GREATER_WEIGHT = 'GREATER_WEIGHT';
export const ORDER_LOWER_WEIGHT = 'LOWER_WEIGHT';
export const REMOVE_FAVOURITES = 'REMOVE_FAVOURITES';
export const ADD_FAVOURITES = 'ADD_FAVOURITES';  
export const SHOW_DETAIL = 'SHOW_DETAIL';
export const MODIFY_LIST_DOGS = 'MODIFY_LIST_DOGS';   
export const RESTOR_LIST_DOGS = 'RESTOR_LIST_DOGS';   
 
